name: Generate CI Documentation
on:
  # Remove before PR
  # push:
  #   branches:
  #     - "issue-*"
  # Remove before PR
  workflow_call:
    inputs:
      commit_resources:
        description: 'Commit the resources after generating them. (Requires the access_token to be passed)'
        required: false
        default: false
        type: boolean
    secrets:
      access_token:
        description: 'The access token to use for commits.'
        required: false
  workflow_dispatch:
    branches:
    - main
    - develop
    - "feature-*"
    - "release-*"
    inputs:
      commit_resources:
        description: 'commit the resources after generating them. Requires a PAT defined as secrets.COMMIT_TOKEN'
        required: true
        default: false
        type: boolean
jobs:
  update_ci_documentation:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate CI Documentation
        uses: Compton-NIST/Inspector@v0.11
        with:
          artifact_name: _docs
          output_path: _docs
          file_prefix: OSCAL
      - name: Make the workflow markdown file a README.md for the directory.
        run: |
          cp _docs/OSCAL.workflows.md _docs/README.md
          rm -f _docs/OSCAL.workflows.md
      - name: Commit Documentation Result (Documents and Diagrams)
        if: github.event.inputs.commit_resources == 'true' || inputs.commit_resources == true
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
        with:
          # repository: ${{ env.CHECKOUT_PATH }}
          create_branch: true
          branch: auto-ci-docs-update
          file_pattern: '*.svg *.md'
          disable_globbing: true
          skip_dirty_check: false
          commit_user_name: OSCAL GitHub Actions Bot
          commit_user_email: oscal@nist.gov
          commit_author: OSCAL GitHub Actions Bot <oscal@nist.gov>
          commit_message: Auto publishing updated CI documentation and diagrams.
      - name: Create Pull Request with Updates
        if: github.event.inputs.commit_resources == 'true' || inputs.commit_resources == true
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          # github_token: ${{ secrets.COMMIT_TOKEN }}
          source_branch: auto-ci-docs-update
          target_branch: main
          title: Update CI Documentation and Diagrams
          body: "**Automated pull request**"
          draft: true
          get_diff: true
          # ignore_users: "dependabot"
